x-podman: # para funcionar com o podman
  in_pod: false

services:
  management-service:
    userns_mode: keep-id:uid=1000,gid=1000 # para funcionar com o podman

    container_name: ladesa-management-service
    user: root

    build:
      context: ../src
      dockerfile: ../.docker/Containerfile
      target: devcontainer

    command:
      - sleep
      - infinity
    depends_on:
      - db
      - rabbitmq
    networks:
      - ladesa-net
    ports:
      - "3701:3701"
      - "9229:9229"

    working_dir: /ladesa/management-service/src/app
    volumes:
      - ..:/ladesa/management-service:z
      - management-service-uploaded-files:/container/uploaded
      - ../volumes/history/root-zsh:/root/.zsh_history:z
      - ../volumes/history/root-bash:/root/.bash_history:z
      - ../volumes/history/happy-zsh:/home/happy/.zsh_history:z
      - ../volumes/history/happy-bash:/home/happy/.bash_history:z
    environment:
      - STORAGE_PATH=/container/uploaded
    env_file:
      - ../.env

  db:
    container_name: ladesa-management-service-db
    image: docker.io/bitnamilegacy/postgresql:15
    volumes:
      - "management-service-db-data:/bitnami/postgresql"
    networks:
      - ladesa-net
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: main
      POSTGRESQL_PASSWORD: 7f22682363b549a389e03b7fe512488b

  rabbitmq:
    container_name: ladesa-rabbitmq
    image: docker.io/rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - ladesa-net
    ports:
      - "5672:5672"
      - "15672:15672"

  chart-db:
    image: ghcr.io/chartdb/chartdb:latest
    ports:
      - "8099:80"

networks:
  ladesa-net:

volumes:
  management-service-db-data:
  management-service-uploaded-files:
