x-podman:
  in_pod: false

services:
  ladesa-management-service:
    container_name: ladesa-management-service
    hostname: ladesa-management-service
    user: root
    build:
      context: ../src
      dockerfile: ../.docker/Containerfile
      target: devcontainer
      args:
        BUN_VERSION: ${BUN_VERSION}
    command:
      - sleep
      - infinity
    depends_on:
      - ladesa-management-service-db
      - sisgea-message-broker
    networks:
      - ladesa-net
    ports:
      - "3701:3701"
      - "9229:9229"
      - "6499:6499"
    working_dir: /ladesa/management-service/src/app
    userns_mode: keep-id:uid=1000,gid=1000
    volumes:
      - ..:/ladesa/management-service:z
      - ladesa-management-service-uploaded-files:/container/uploaded
      - ../volumes/history/root-zsh:/root/.zsh_history:z
      - ../volumes/history/root-bash:/root/.bash_history:z
      - ../volumes/history/happy-zsh:/home/happy/.zsh_history:z
      - ../volumes/history/happy-bash:/home/happy/.bash_history:z
    environment:
      - STORAGE_PATH=/container/uploaded
    env_file:
      - ../.env

  ladesa-management-service-db:
    image: docker.io/bitnamilegacy/postgresql:15
    container_name: ladesa-management-service-db
    volumes:
      - "ladesa-management-service-db-data:/bitnami/postgresql"
    networks:
      - ladesa-net
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: main
      POSTGRESQL_PASSWORD: 7f22682363b549a389e03b7fe512488b
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  sisgea-message-broker:
    image: docker.io/rabbitmq:3-management-alpine
    container_name: sisgea-message-broker
    hostname: sisgea-message-broker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - ladesa-net
    ports:
      - "5672:5672"
      - "15672:15672"
#    healthcheck:
#      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-management-service-db-data:
  ladesa-management-service-uploaded-files:
