name: "[DEV] Build, Push & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-deploy.dev.yml
      - .deploy/**/*
      - app/**/*

concurrency:
  group: build-deploy-dev

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  ci:
    name: "CI: Build & Push"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: "[CI] Checkout do código-fonte"
        uses: actions/checkout@v5

      - name: "[CI] Set up QEMU"
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: "[CI] Set up Docker Buildx"
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: "[CI] Autenticação no GitHub Container Registry"
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: "[CI] Construção e publicação da imagem de contêiner"
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./app/
          target: service-runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:development
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/management-service:cache-development,mode=max

  cd:
    name: "CD: Deploy"
    runs-on: dev-deploy
    permissions:
      contents: read
    needs: [ ci ]
    environment:
      name: development
      url: ${{ vars.DEPLOY_URL }}
    steps:
      - name: "[CD] Checkout do código-fonte"
        uses: actions/checkout@v5

      - name: "[CD] Implantação"
        shell: bash
        working-directory: ./.deploy/development/
        run: bash ./deploy.sh
